version: 0.2

env:    
  variables:
    s3_bucket: "$s_bucket"

phases:

  install:
    commands:
      - npm i
      
  build:
    commands:
      - cd app/web
      - npm i 
      - npm run prod      
      - cd build
      - aws s3 rm s3://${s3_bucket} --recursive
      - aws s3 sync . s3://${s3_bucket}
  
artifacts:
  files:
    - build/**/*
